### ISSUE TITLE
Cuidado con las credenciales

### ISSUE THREAD

**Issue by Luis-Munu** [AndoniHQ/Pccomponentes-Tracker#1]
Buenas Andoni,

En uno de los últimos commits "Password fix", se ven dos de tus correos y una contraseña.
Aunque borraste los datos del archivo, siguen visibles en los diffs de este.

Esta issue solo es para avisarte de esto, cambia la contraseña o reescribe el historial de commits desde un punto anterior.

Un saludo y buen proyecto.

**Comment by AndoniHQ** [comment]
Buenas Luis,

Era una cuenta de correo para pruebas pero al darme cuenta de que estaban las credenciales las quite y cambie la password. Aun así tienes razón he modificado la rama para deshacerme del historial de commits.

Muchas gracias!
